image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - init: |
      npm install
      sudo apt-get update
      sudo service mongodb start
      echo "MONGO_URI=mongodb://localhost:27017/urlshortener" > .env
  - command: node index.js
