image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - init: |
      npm install
      sudo apt-get update
      sudo service mongodb start
      echo "MONGO_URI=mongodb+srv://<dbpassword>@cluster0.oglmmzf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" > .env
  - command: node index.js
